//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internet_Check.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SettingInterval {
            get {
                return ((int)(this["SettingInterval"]));
            }
            set {
                this["SettingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingDarkmode {
            get {
                return ((bool)(this["SettingDarkmode"]));
            }
            set {
                this["SettingDarkmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingWindowsStart {
            get {
                return ((bool)(this["SettingWindowsStart"]));
            }
            set {
                this["SettingWindowsStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingHideWhenMin {
            get {
                return ((bool)(this["SettingHideWhenMin"]));
            }
            set {
                this["SettingHideWhenMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingTask {
            get {
                return ((string)(this["SettingTask"]));
            }
            set {
                this["SettingTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Next")]
        public string SettingDoubleCheckServer {
            get {
                return ((string)(this["SettingDoubleCheckServer"]));
            }
            set {
                this["SettingDoubleCheckServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingUseAlternativePingMethod {
            get {
                return ((bool)(this["SettingUseAlternativePingMethod"]));
            }
            set {
                this["SettingUseAlternativePingMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBoxAllPingResults {
            get {
                return ((bool)(this["SettingCheckBoxAllPingResults"]));
            }
            set {
                this["SettingCheckBoxAllPingResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingCheckBoxShowMinimizedInfo {
            get {
                return ((bool)(this["SettingCheckBoxShowMinimizedInfo"]));
            }
            set {
                this["SettingCheckBoxShowMinimizedInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SettingTextBoxTaskSchedulerStopTaskAfterDays {
            get {
                return ((int)(this["SettingTextBoxTaskSchedulerStopTaskAfterDays"]));
            }
            set {
                this["SettingTextBoxTaskSchedulerStopTaskAfterDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBoxDisallowStartIfOnBatteries {
            get {
                return ((bool)(this["SettingCheckBoxDisallowStartIfOnBatteries"]));
            }
            set {
                this["SettingCheckBoxDisallowStartIfOnBatteries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBoxStopIfGoingOnBatteries {
            get {
                return ((bool)(this["SettingCheckBoxStopIfGoingOnBatteries"]));
            }
            set {
                this["SettingCheckBoxStopIfGoingOnBatteries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBoxStopOnIdleEnd {
            get {
                return ((bool)(this["SettingCheckBoxStopOnIdleEnd"]));
            }
            set {
                this["SettingCheckBoxStopOnIdleEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingUseCustomServers {
            get {
                return ((bool)(this["SettingUseCustomServers"]));
            }
            set {
                this["SettingUseCustomServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection SettingCustomServersCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SettingCustomServersCollection"]));
            }
            set {
                this["SettingCustomServersCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingDisableUpdateNotifications {
            get {
                return ((bool)(this["SettingDisableUpdateNotifications"]));
            }
            set {
                this["SettingDisableUpdateNotifications"] = value;
            }
        }
    }
}
